/**
 * Canonical API error codes. Status mapping lives in `server/http/errors.ts`.
 */
export enum ErrorCode {
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  ONBOARDING_INCOMPLETE = 'ONBOARDING_INCOMPLETE',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMITED = 'RATE_LIMITED',
  UPSTREAM_ERROR = 'UPSTREAM_ERROR',
  INTERNAL = 'INTERNAL',
}
